# Generated by Django 6.1 on 2026-08-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("short_description", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Example: fa-solid fa-laptop",
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="platforms/"),
                ),
                ("url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
