# Generated by Django 6.1 on 2026-08-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="featured",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="platform",
            name="icon",
            field=models.CharField(
                blank=True, help_text="Font Awesome icon class", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="platform",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="platform",
            name="url",
            field=models.URLField(blank=True, help_text="URL of the platform"),
        ),
    ]
